// <auto-generated />
using System;
using System.Collections.Generic;
using Domain.Entities;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.BehaviorCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsAntecedent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_antecedent");

                    b.Property<bool>("IsBehavior")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_behavior");

                    b.Property<bool>("IsConsequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_consequence");

                    b.Property<string>("LabelGroup")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("label_group");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("PointValue")
                        .HasColumnType("integer")
                        .HasColumnName("point_value");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer")
                        .HasColumnName("teacher_id");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("behavior_categories", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.BehaviorLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<string>("AiTags")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("ai_tags");

                    b.Property<string>("Antecedent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("antecedent");

                    b.Property<int>("BehaviorCategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("behavior_category_id");

                    b.Property<string>("BehaviorDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("behavior_description");

                    b.Property<string>("Consequence")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("consequence");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("LessonId")
                        .HasColumnType("integer")
                        .HasColumnName("lesson_id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at");

                    b.Property<string>("RawTranscription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("raw_transcription");

                    b.Property<int>("SeverityLevel")
                        .HasColumnType("integer")
                        .HasColumnName("severity_level");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer")
                        .HasColumnName("student_id");

                    b.HasKey("Id");

                    b.HasIndex("BehaviorCategoryId");

                    b.HasIndex("LessonId");

                    b.HasIndex("StudentId");

                    b.ToTable("behavior_logs", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.ToTable("classes", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ContextBehaviorMap", b =>
                {
                    b.Property<int>("TeachingContextId")
                        .HasColumnType("integer")
                        .HasColumnName("teaching_context_id");

                    b.Property<int>("BehaviorCategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("behavior_category_id");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.HasKey("TeachingContextId", "BehaviorCategoryId");

                    b.HasIndex("BehaviorCategoryId");

                    b.ToTable("context_behavior_maps", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.InterventionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BehaviorLogId")
                        .HasColumnType("integer")
                        .HasColumnName("behavior_log_id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("EffectivenessRating")
                        .HasColumnType("integer")
                        .HasColumnName("effectiveness_rating");

                    b.Property<string>("SuggestedIntervention")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("suggested_intervention");

                    b.HasKey("Id");

                    b.HasIndex("BehaviorLogId");

                    b.ToTable("intervention_logs", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("EndAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("end_at");

                    b.Property<int>("LessonStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("lesson_status");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("StartAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("start_at");

                    b.Property<int>("TeachingContextId")
                        .HasColumnType("integer")
                        .HasColumnName("teaching_context_id");

                    b.HasKey("Id");

                    b.HasIndex("TeachingContextId");

                    b.ToTable("lessons", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.LessonSummary", b =>
                {
                    b.Property<int>("LessonId")
                        .HasColumnType("integer")
                        .HasColumnName("lesson_id");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer")
                        .HasColumnName("student_id");

                    b.Property<int?>("FinalScore")
                        .HasColumnType("integer")
                        .HasColumnName("final_score");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.HasKey("LessonId", "StudentId");

                    b.HasIndex("StudentId");

                    b.ToTable("lesson_summaries", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset?>("ExpiredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("expired_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP + INTERVAL '7 days'");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_revoked");

                    b.Property<int?>("ReplacedByTokenId")
                        .HasColumnType("integer")
                        .HasColumnName("replaced_by_token_id");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer")
                        .HasColumnName("teacher_id");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("token");

                    b.HasKey("Id");

                    b.HasIndex("ReplacedByTokenId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.SeatAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<int>("OrdinalIndex")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal_index");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer")
                        .HasColumnName("student_id");

                    b.Property<int>("TeachingContextId")
                        .HasColumnType("integer")
                        .HasColumnName("teaching_context_id");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("TeachingContextId", "OrdinalIndex")
                        .IsUnique()
                        .HasFilter("ordinal_index <> -1");

                    b.HasIndex("TeachingContextId", "StudentId")
                        .IsUnique();

                    b.ToTable("seat_assignments", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ShareCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset?>("ExpiredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("expired_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP + INTERVAL '24 hours'");

                    b.Property<int>("SourceContextId")
                        .HasColumnType("integer")
                        .HasColumnName("source_context_id");

                    b.HasKey("Id");

                    b.HasIndex("SourceContextId");

                    b.ToTable("share_codes", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("date")
                        .HasColumnName("birthday");

                    b.Property<int>("ClassId")
                        .HasColumnType("integer")
                        .HasColumnName("class_id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("full_name");

                    b.Property<List<StudentSensitivityProfile>>("StudentSensitivityProfiles")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("student_sensitivity_profile");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.ToTable("students", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("full_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("teachers", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.TeachingContext", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("integer")
                        .HasColumnName("class_id");

                    b.Property<string>("ContextName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("context_name");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at");

                    b.Property<List<EnvironmentalAsset>>("EnvironmentalAssets")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("environmental_assets");

                    b.Property<int>("NumCols")
                        .HasColumnType("integer")
                        .HasColumnName("num_cols");

                    b.Property<int>("NumRows")
                        .HasColumnType("integer")
                        .HasColumnName("num_rows");

                    b.Property<int>("SeatsPerTable")
                        .HasColumnType("integer")
                        .HasColumnName("seats_per_table");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer")
                        .HasColumnName("teacher_id");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("TeacherId");

                    b.ToTable("teaching_contexts", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.BehaviorCategory", b =>
                {
                    b.HasOne("Domain.Entities.Teacher", "Teacher")
                        .WithMany("BehaviorCategories")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Domain.Entities.BehaviorLog", b =>
                {
                    b.HasOne("Domain.Entities.BehaviorCategory", "BehaviorCategory")
                        .WithMany("BehaviorLogs")
                        .HasForeignKey("BehaviorCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Lesson", "Lesson")
                        .WithMany("BehaviorLogs")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Student", "Student")
                        .WithMany("BehaviorLogs")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BehaviorCategory");

                    b.Navigation("Lesson");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Domain.Entities.Class", b =>
                {
                    b.HasOne("Domain.Entities.Teacher", "Teacher")
                        .WithMany("Classes")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Domain.Entities.ContextBehaviorMap", b =>
                {
                    b.HasOne("Domain.Entities.BehaviorCategory", "BehaviorCategory")
                        .WithMany("ContextBehaviorMaps")
                        .HasForeignKey("BehaviorCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.TeachingContext", "TeachingContext")
                        .WithMany("ContextBehaviorMaps")
                        .HasForeignKey("TeachingContextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BehaviorCategory");

                    b.Navigation("TeachingContext");
                });

            modelBuilder.Entity("Domain.Entities.InterventionLog", b =>
                {
                    b.HasOne("Domain.Entities.BehaviorLog", "BehaviorLog")
                        .WithMany("InterventionLogs")
                        .HasForeignKey("BehaviorLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BehaviorLog");
                });

            modelBuilder.Entity("Domain.Entities.Lesson", b =>
                {
                    b.HasOne("Domain.Entities.TeachingContext", "TeachingContext")
                        .WithMany("Lessons")
                        .HasForeignKey("TeachingContextId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TeachingContext");
                });

            modelBuilder.Entity("Domain.Entities.LessonSummary", b =>
                {
                    b.HasOne("Domain.Entities.Lesson", "Lesson")
                        .WithMany("LessonSummaries")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Student", "Student")
                        .WithMany("LessonSummaries")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Domain.Entities.RefreshToken", "ReplacedByToken")
                        .WithMany()
                        .HasForeignKey("ReplacedByTokenId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.Teacher", "Teacher")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReplacedByToken");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Domain.Entities.SeatAssignment", b =>
                {
                    b.HasOne("Domain.Entities.Student", "Student")
                        .WithMany("SeatAssignments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.TeachingContext", "TeachingContext")
                        .WithMany("SeatAssignments")
                        .HasForeignKey("TeachingContextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("TeachingContext");
                });

            modelBuilder.Entity("Domain.Entities.ShareCode", b =>
                {
                    b.HasOne("Domain.Entities.TeachingContext", "TeachingContext")
                        .WithMany("ShareCodes")
                        .HasForeignKey("SourceContextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TeachingContext");
                });

            modelBuilder.Entity("Domain.Entities.Student", b =>
                {
                    b.HasOne("Domain.Entities.Class", "Class")
                        .WithMany("Students")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("Domain.Entities.TeachingContext", b =>
                {
                    b.HasOne("Domain.Entities.Class", "Class")
                        .WithMany("TeachingContexts")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Teacher", "Teacher")
                        .WithMany("TeachingContexts")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Domain.Entities.BehaviorCategory", b =>
                {
                    b.Navigation("BehaviorLogs");

                    b.Navigation("ContextBehaviorMaps");
                });

            modelBuilder.Entity("Domain.Entities.BehaviorLog", b =>
                {
                    b.Navigation("InterventionLogs");
                });

            modelBuilder.Entity("Domain.Entities.Class", b =>
                {
                    b.Navigation("Students");

                    b.Navigation("TeachingContexts");
                });

            modelBuilder.Entity("Domain.Entities.Lesson", b =>
                {
                    b.Navigation("BehaviorLogs");

                    b.Navigation("LessonSummaries");
                });

            modelBuilder.Entity("Domain.Entities.Student", b =>
                {
                    b.Navigation("BehaviorLogs");

                    b.Navigation("LessonSummaries");

                    b.Navigation("SeatAssignments");
                });

            modelBuilder.Entity("Domain.Entities.Teacher", b =>
                {
                    b.Navigation("BehaviorCategories");

                    b.Navigation("Classes");

                    b.Navigation("RefreshTokens");

                    b.Navigation("TeachingContexts");
                });

            modelBuilder.Entity("Domain.Entities.TeachingContext", b =>
                {
                    b.Navigation("ContextBehaviorMaps");

                    b.Navigation("Lessons");

                    b.Navigation("SeatAssignments");

                    b.Navigation("ShareCodes");
                });
#pragma warning restore 612, 618
        }
    }
}
