global using AutoMapper;
global using AutoMapper.QueryableExtensions;
global using Microsoft.EntityFrameworkCore;
global using FluentValidation;
global using FluentValidation.Results;
global using MediatR;
global using Domain.Entities;
global using Domain.Enums;
global using Application.Common.Interfaces;
